### ISSUE TITLE
browsing pathways

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#100]
Couple of comments on the pathway view: 

1. let's remove large pathways with >500 genes and small pathways with <10 genes. 
2. let's rank the pathways according to some score from Marta's calculations. One option:

score = min(rankCancer, rankClinVar), where lower score is better, and rankX means that this pathway got the Xth rank on the ordering of p-values from the pathway analysis. 

3. At the bottom of the page, we should note that pathways are ranked according to their importance in PTM mutations in cancer (TCGA) or in genetic disease (ClinVar). 

ps - do we need ClinVar pathway scores from Marta?

**Comment by krassowski** [comment]
Should this supersede the current implementation: https://activedriverdb.org/pathways/with_significant_genes/Cancer%20%28TCGA%20PanCancerAtlas%29, or should the two coexist?

**Comment by reimand0** [comment]
I don't know which ranking makes more sense, the score-based or the PTM.mut.count-based. We just want to provide the most interesting genes at the top. Perhaps we can keep the current PTM.mut.count-based ranking for now. 

We could also use color to highlight the gene names with larger number of PTM SNVs.

**Comment by krassowski** [comment]
Some previous discussion on pathways was in #88. The pre-computed pathways list (so option 2) was added in #162. Let's have both options co-existing:
- I will expose the pre-computed list on the front page
- the old list based on >10, < 500 genes in pathways with >= 5 significant genes will be still available for backwards reference
