### ISSUE TITLE
editing network layout

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#101]
following up on Erik's comment - it may be useful to allow user lift things around in the network view. one option is to stop reverting to the pre-defined layout once user starts to modify the layout, and have a mechanism/button to return to that pre-defined layout (although then the user could just refresh the page).

**Comment by krassowski** [comment]
Done. Once a node is moved it stays in the new position. User can revert this action by shift-clicking on the node. I also added a summary of controls to network page: https://activedriverdb.org/network/show/NM_000546
