### ISSUE TITLE
searching by pathway

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#102]
I like the searching by pathways on this page: https://activedriverdb.org/pathways/all/. Two questions:

1. what are the results ranked by? Maybe minimal edit distance to pathway name would be the best. try _cell cycle_ and see lots of results with complex ones ranked to the top. 

2. Can we add the pathway search function to the main search box on the front page? We could use the syntax of double quotes like "cell cycle", for example.

**Comment by reimand0** [comment]
clicking on pathway gene should directly jump to the sequence view of preferred isoform, not an intermediate isoform page. we should reduce long click series. 

alternative isoforms are available on the sequence view page, correct?

**Comment by krassowski** [comment]
I got both working on my local machine, but I have problems with function scoring edit distance on production.

I use MySQL function UDF which implements Levensthein distance ratio. It works well on my laptop (I have MariaDB drop-in replacement for MySQL installed) but returns insane values on our production server (it resembles an integer overflow). We may want to migrate to MariaDB or PostgreSQL (which  has built-in levenshtein and would allow using view tables finally, so we could get significant performance boost), but it would require a week or so to complete. Maybe upgrading MySQL will suffice to resolve the problem.

Anyway the take-away is that the edit-distance sort is implemented but not functional on production yet.

**Comment by reimand0** [comment]
I think upgrading the entire database engine is a little risky so shortly
before the submission. Can you please request a database upgrade instead
from the IT help desk? we can consider the new DB engine once the rush of
the manuscript preparation is complete.

**Comment by krassowski** [comment]
I updated the MySQL database and found the root of the problem - it was just wrong type specified for `levenshtein_ratio` UDF (and the strange thing is it was working well on MariaDB). The edit-distance sorting works now as expected.

**Comment by reimand0** [comment]
Well done!
