### ISSUE TITLE
long names of genes

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#103]
Adding long names of genes is great, thanks! couple of comments: 

1. we should add the long name also to the network view. the longer description could be added below the network canvas. 

2. the current long name is isoform specific not gene specific, correct? I think the headline could just have the gene-specific name and below in a smaller font the isoform specific extension. For example, 

# PTPN11 (NM_002834) - Tyrosine-Protein Phosphatase Non-Receptor Type 11 
Isoform 1

**Comment by krassowski** [comment]
2.Yes, that's correct.  Will something like:

## PTPN11 (NM_002834) - Protein Tyrosine Phosphatase, Non-Receptor Type 11
Tyrosine-Protein Phosphatase Non-Receptor Type 11 Isoform 1

do the job? Please notice the difference between the gene-specific name and  the isoform specific - it's often not only + 'isoform X' in isoform name, hence it may be difficult to implement it exactly as in your example (some genes have isoforms indexed by numbers some by letters some don't have at all).

**Comment by reimand0** [comment]
Yes that sounds ok

Jüri

**Comment by krassowski** [comment]
1. Did you mean to add the full summary box to network view, like this:

![screenshot from 2017-07-19 22-41-02](https://user-images.githubusercontent.com/5832902/28388727-f196ecac-6cd3-11e7-890f-ac4873b6942a.png)?

2. Done

**Comment by reimand0** [comment]
This looks good, thanks. 

slightly off-topic but the screenshot shows it well: we should change the color of the text of Disorder bar to black or something that shows well on red and gray. The current version can be difficult to read.

**Comment by krassowski** [comment]
I added the summary box and changed color of disorder text to black (1f92cd27cddb4ca86145809418c3f8682f0b31bf). I will close the issue for now. In case of future requests please reopen.
