### ISSUE TITLE
legend on network view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#104]
We should add meaning of colored and dashed edges to the legend on network view.

**Comment by reimand0** [comment]
also in the legend, "PTM Site color corresponds to type". I think this corresponds to PTM mutation type (direct, distal, proximal, rewiring) rather than PTM type (ub, ac, me, ph). Correct? should be rephrased like 

"color of square corresponds to impact of mutations on PTM site" 
darkred - 
red -
orange - 
yellow -

**Comment by krassowski** [comment]
> We should add meaning of colored and dashed edges to the legend on network view.

Done.

>  I think this corresponds to PTM mutation type (direct, distal, proximal, rewiring) rather than PTM type (ub, ac, me, ph). Correct? 

Yes, that's right, I updated the legend.

The legend on network view takes a lot of space now, we may want to collapse it.
