### ISSUE TITLE
clicking to mutations in network view?

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#105]
is it possible to see what mutations correspond to sites in the network view? 

Maybe the mouse-over box could include a link "show mutations" which points to the mutations table in sequence view, anchoring on the row that carries the first mutation in this site.

**Comment by reimand0** [comment]
Adding that it would be useful to be able to better understand colored edges as well (those that lead to MIMP gains/losses). Maybe mousing over would open a pop-up box with the logo+info, and user could click on that box to get to table in sequence view, as described above. let me know if you have better ideas though!

**Comment by krassowski** [comment]
> is it possible to see what mutations correspond to sites in the network view?

Yes. I added a table with mutations to the site tooltip as an experiment. I tried to keep it small, but if it is too big we may collapse it and expand after a click (e.g. we may add a button saying "click to show mutations"). And of course we may reduce it to a single link to sequence view table. What do you think?

To make clicking on links possible I had to change click event handling. Previously a click was interpreted as "do not hide this tooltip so user can select text" on all nodes and "expose site showing subnetwork of interactions around this site". To prevent simultaneous tooltip pop-up while exposing a site, the tooltip sticking got lower priority, hence it was hard to select a text or click a link. Anyway I resolved this conflict, remapping the **"expose subnetwork" action to "ctrl + click"**. Please, let me know if you wish it to be done in another way.

**Comment by reimand0** [comment]
This looks great too. I would add to the tooltip a link to the mutations table in the sequence view. [show mutations in sequence view]
