### ISSUE TITLE
exporting network view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#106]
can we export the network in the network view as a text file, perhaps using the following columns?

target_protein target_site target_site_type target_site_mutation_impact bound_enzyme

**Comment by krassowski** [comment]
I started implementing this. Should we duplicate entries for all impacts that we see on given site, or only use the most severe consequence (impact)? I am referring to proposed `target_site_mutation_impact` column. Let's look at 305 K from TP53; there are two mutations within a range of +/- 7 from this site, one with "proximal" and one with "distal" impact. should this render into:

```
NM_000546    305K     acetylation,ubiquitination    distal    EP300
NM_000546    305K     acetylation,ubiquitination    proximal    EP300
```

or just into:

```
NM_000546    305K     acetylation,ubiquitination    proximal    EP300
```

**Comment by krassowski** [comment]
Did I understand the first column properly anyway - will it always have the same value for a single protein (unless we implement second shell i.e. showing all interactions of kinases)?

**Comment by reimand0** [comment]
yes, the first column will be the same. but we should still keep it - this
allows users to concatenate multiple networks for example. Also network
visualisation with Cytoscape uses this file format.

**Comment by krassowski** [comment]
So assuming that we only need the most severe impact, it is already implemented and ready to use on production: this is the "TSV file". Should I change the refseq id to gene name?

![screenshot from 2017-07-21 22-05-16](https://user-images.githubusercontent.com/5832902/28480391-c3925bd2-6e60-11e7-8796-fc711d0955fc.png)

**Comment by reimand0** [comment]
Yes symbols are better for networks. You can keep refseq too as additional columns. 

Jüri

**Comment by krassowski** [comment]
Done. If any amendments are needed, please reopen this issue.
