### ISSUE TITLE
search bar?

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#108]
is the main search bar on the front page different from the search bar in the top right corner? it would be the best that the topright bar supports the same flexible search as the main bar (mutations in dna and protein, gene symbols, refseq ids, pathways). is this easy to achieve?

**Comment by krassowski** [comment]
I made the top-right search bar to use exactly the same logic as the main bar. The pathways searching is not implemented yet (generally, neither of search bars supports its yet) but it should be easy to add.

For the top-right bar: do we want to expand width of the bar with results so badges indicating mutations and isoform status display nicely in one line or do we want to hide those badges in top-right quick search results?

**Comment by reimand0** [comment]
I think we can expand it a bit however we should keep some minimum screen
width in mind. fitting all examples is not a priority.

**Comment by krassowski** [comment]
Already fully implemented.
