### ISSUE TITLE
search by disease

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#109]
More search requests - is it possible to provide a keyword like leukemia or "congenital syndrome" and get all the genes that have mutations with that kind in either ClinVar or TCGA? 

these various searches are the principal decision points for users to either love this database or abandon it.

What do you think, is it feasible to implement this without major work on the database structure?

**Comment by reimand0** [comment]
we should probably constrain display or results by either retrieving first few results or specifying size of minimal query size

**Comment by reimand0** [comment]
Thinking about this - we have two distinct search areas, the clinvar annotation field, and the TCGA cancer type subset. One option to solve this is the following: 

user searches for the term 'breast'. This does two things (a) looks up if any TCGA cancer type matches that keyword (b) looks up if any genes with clinVar mutations match that keyword. 

 - on top of page: did you mean cancer mutations of Breast invasive carcinoma (BRCA)? Link leads to a new page with top 100 genes with most PTM SNVs in that cancer type
 - after that message, a table with genes from ClinVar follows.

**Comment by krassowski** [comment]
Search by cancer is in. It redirects to TCGA genes list with appropriate cancer pre-selected.

**Comment by reimand0** [comment]
I tried a couple of queries: "noonan" and "breast" and "leukemia". The
queries are not responsible, however maybe the DB is currently being
updated.

**Comment by krassowski** [comment]
> I tried a couple of queries: "noonan" and "breast" and "leukemia". The
> queries are not responsible, however maybe the DB is currently being
> updated.

Disease search was not implemented until today, but "breast" should have returned result like this:

![screenshot from 2017-08-07 23-16-49](https://user-images.githubusercontent.com/5832902/29046179-915895b4-7bc6-11e7-9991-aec124a73031.png)

Is it working for you now? (Right now the results should include also disease too). If not, in which browser are you experiencing this issue? (I tested with Safari 9.1, Firefox 54, Chrome 60, Opera 46, Yandex 14.12 on El Captain; the same on Sierra (but using Safari 10.1) + IE 11 and Edge 15 on Windows 10 + my casual Ubuntu/Fedora browsers stack).

--

I just added and deployed searching by disease. Please see following examples:

A user can start by typing in disease name. Partial matches (prefix and suffix) are supported:

![screenshot from 2017-08-07 23-00-05](https://user-images.githubusercontent.com/5832902/29045773-124893ec-7bc5-11e7-9403-1d6c174aa5fd.png)


It directs to the list of genes significant for ClinVar mutations, filtered by presence of mutations associated with given disease. The first entry shown above it will lead to [this view](https://activedriverdb.org/gene/list/Clinical%20%28ClinVar%29?filters=Mutation.sources%3Ain%3AClinVar%3BMutation.disease_name%3Ain%3ACystic+fibrosis).

If the user proceeds with pressing space, a suggestion to look for genes with mutations associated with matched disease (any of matching disease, really) is shown:

![screenshot from 2017-08-07 23-00-30](https://user-images.githubusercontent.com/5832902/29045849-54df0664-7bc5-11e7-92f5-317c08cebb08.png)

If the user starts to follow presented schema they will quickly be presented with matching genes:

![screenshot from 2017-08-07 23-01-12](https://user-images.githubusercontent.com/5832902/29045913-80247ea8-7bc5-11e7-915f-d791cb5c9b5e.png)

The user can precise the query further. Please not that the results are including all matching diseases (below: all diseases matching "cystic" with mutated genes matching "C"): 

![screenshot from 2017-08-07 23-01-32](https://user-images.githubusercontent.com/5832902/29045938-a218e134-7bc5-11e7-8c10-c79e9863df20.png)

Clicking on a result will lead to the sequence view. For the first entry above it is [sequence view of CFTR](https://activedriverdb.org/sequence/show/NM_000492?filters=Mutation.sources:in:ClinVar;Mutation.disease_name:in:Cystic%20fibrosis), with all Cystic fibrosis-associated mutations shown.

**Comment by krassowski** [comment]
Closing for now, please feel free to reopen if any improvement is needed.
