### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by idzneladze** [reimandlab/ActiveDriverDB#110]
Hi  ActiveDriverDB team,

The sorts in the "all genes" and "all pathways" sometimes take ~30 seconds to complete but do not display a loading icon. This initially gave the impression that these sorts are not working at all. Would it be possible to add a loading icon if the search will take a while to complete?

https://activedriverdb.org/pathways/all/
https://activedriverdb.org/pathways/with_significant_genes/Cancer%20%28TCGA%20PanCancerAtlas%29

---
Ubuntu 16.04.2 LTS
Google Chrome Version 57.0.2987.133 (64-bit)

**Comment by krassowski** [comment]
Hi idzneladze,

Thank you for your suggestion. I agree with your point. I turned of silent sorting until a faster sorting is available.
