### ISSUE TITLE
network view legend

### ISSUE THREAD

**Issue by idzneladze** [reimandlab/ActiveDriverDB#111]
The PTM interaction network visualisation figure contains some features which are not explained in the legend:

- PTM mutation box colours (what are the differences between red, burgundy, grey, and yellow?)
- Kinase shapes (why are some of them octagons?)
- Kinase-PTM mutation lines (why are some of them red and dotted?)

Would it be possible to add an explanation for all these features?

---
Ubuntu 16.04.2 LTS
Google Chrome Version 57.0.2987.133 (64-bit)

**Comment by krassowski** [comment]
> PTM mutation box colours (what are the differences between red, burgundy, grey, and yellow?)

Done.

> Kinase shapes (why are some of them octagons?)

Octagons represents kinase families (or groups, the naming convention varies). If you click on one, the known kinases belonging to this group will pop up. (@reimand0, I can add this to legend too, but we are running out of space).

> Kinase-PTM mutation lines (why are some of them red and dotted?)

Done. The width of dashed lines is dependent on the number of "loss" predictions.

**Comment by idzneladze** [comment]
Thank you, I will include this information in the tutorial and in the [?] icon text.
