### ISSUE TITLE
two search results of BRAF V600E

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#112]
I received conflicting results when searching for BFAR V600E mutation.
![screen shot 2017-07-14 at 4 27 51 pm](https://user-images.githubusercontent.com/19268349/28229614-6c07a7fa-68b1-11e7-8c41-81ee5c9fe59b.png)
![screen shot 2017-07-14 at 4 27 41 pm](https://user-images.githubusercontent.com/19268349/28229615-6c087540-68b1-11e7-8577-d531ffead650.png)

**Comment by krassowski** [comment]
I fixed it already. Reference check was performed against 0-based python structure and I missed it when testing TP53 R282W as there is arginine at 283 too. I apologize for the silly mistake.

**Comment by reimand0** [comment]
thanks!
