### ISSUE TITLE
Example Order

### ISSUE THREAD

**Issue by idzneladze** [reimandlab/ActiveDriverDB#116]
For consistency, would it be possible to switch the order of the example plots on the homepage? (show the Sequence plot on the left, and the Network plot on the right). The Sequence View is always on the left (both in tab order, and example order) so perhaps it would be better to stay consistent

----
Ubuntu 16.04.2 LTS
Google Chrome Version 57.0.2987.133 (64-bit)

**Comment by krassowski** [comment]
I agree. I switched the examples.
