### ISSUE TITLE
Network of MIMP predicted kinases

### ISSUE THREAD

**Issue by krassowski** [reimandlab/ActiveDriverDB#121]
We may add an additional "network view" to show novel interactions predicted by MIMP (currently we only show losses in network view; gains are accessible only in sequence view).

**Comment by krassowski** [comment]
@reimand0 this is mostly complete: https://activedriverdb.org/network/predicted/NM_007294.

I added families so we show all information predicted with MIMP. If there are too many nodes on some networks, we could group kinases by families (i.e. hide kinases which belong to families until a family is tapped on) or hide the family (group) nodes completely.

Please, let me know of any comments and requests.

**Comment by krassowski** [comment]
I used green color and rounded dashed line (for predicted gains). There are more losses shown in predicted network than in the normal one as in the normal there are shown only kinases which are both: known to interact with given site and with predicted loss.

**Comment by reimand0** [comment]
this looks great, thanks! There is one strange feature in the visualisation - the network appears to be duplicated with every node represented twice. 
<img width="895" alt="screen shot 2017-08-06 at 2 22 02 pm" src="https://user-images.githubusercontent.com/19268349/29002791-2041506e-7ab3-11e7-9e4b-9a285862258e.png">
<img width="887" alt="screen shot 2017-08-06 at 2 21 37 pm" src="https://user-images.githubusercontent.com/19268349/29002792-20429cb2-7ab3-11e7-8129-9e2da731d26b.png">

**Comment by reimand0** [comment]
let's update the titles in the tabs
network view, experimental
network view, MIMP-predicted

**Comment by krassowski** [comment]
In which browsers did you get the duplicated nodes?



6 sie 2017 1:26 PM "reimand0" <notifications@github.com> napisał(a):

**Comment by reimand0** [comment]
chrome on mac

**Comment by reimand0** [comment]
safari does not have that problem

**Comment by krassowski** [comment]
I changed the tab names.

I tested the network with Chrome 57, 58, 59, 60 and 61 developer on Sierra and I cannot reproduce the problem with nodes duplication. Also tested Chrome 60 on El Capitan, Yosemite and Mavericks.
