### ISSUE TITLE
legend placement on views

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#123]
We have a nice set of legends now in sequence and network view, thanks! 

One comment: They are quite prominent in the layout. Maybe we should move the filters box on the left above the legend box in the sequence and also the network view. Similarly, in the network view, the usage summary could move below the protein description box.

The rationale is the following - users who are already familiar with the legend will need less effort to find the information they need.

**Comment by krassowski** [comment]
I moved legend below filters and moved network usage summary below protein summary.

**Comment by krassowski** [comment]
In case of further comments or questions please reopen.
