### ISSUE TITLE
order pathway genes by #PTMSNVs

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#125]
what are the genes currently ordered by? Would it make sense to order and visualise these by number of PTM SNVs in them? Because this is just browsing purposes, we could order by total PTM SNVs not only in some dataset. 

https://activedriverdb.org/pathways/reactome/1640170/

**Comment by krassowski** [comment]
Done. Implemented as a sortable table with default descending order by PTM mutations count. The count includes all mutations affecting PTM sites as it is done consistently in other places too.
