### ISSUE TITLE
[?] icon addition

### ISSUE THREAD

**Issue by idzneladze** [reimandlab/ActiveDriverDB#126]
Please insert a [?] icon next to the option headings in the "Data Filters" section (same as seen in the "Legend" section). For example, please insert [?] icon next to "PTM mutations only", "Mutation dataset", "Cancer type", "Type of PTM site", etc.. 

Otherwise there would be an excessive amount of text tethered to the [?] icon next to "Data Filters" 

Thank you

**Comment by krassowski** [comment]
Done with e06e4fe9f21a82c42abc0a33a09782754d1e1cb9. Is there any other place where you would like to add [?] icons?

**Comment by krassowski** [comment]
Please reopen if needed.
