### ISSUE TITLE
Additional [?] icon requent

### ISSUE THREAD

**Issue by idzneladze** [reimandlab/ActiveDriverDB#127]
If possible, I would like to request the addition of two new [?] icons:

>Homepage>About the data>Mutations>[?]
i.e. next to the header "Mutations" in the "About the data" summary table

>Sequence View>Mutation table>[?]
i.e. anywhere in the header of the summary table on the Sequence View page - would like to explain what the table is at this [?] icon.

Thank you

**Comment by krassowski** [comment]
I added requested icons.
