### ISSUE TITLE
MIMP gains/losses inconsistency 

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#129]
There is an inconsistency between predicted gains and losses of network interactions in sequence view and network view:

In network view, the site at S168 has all gains of CDKs and MAPKs:
https://activedriverdb.org/network/predicted/NM_000551
<img width="219" alt="screen shot 2017-08-15 at 5 37 59 am" src="https://user-images.githubusercontent.com/19268349/29310509-f495dee2-817b-11e7-93ec-57d6280c2842.png">

In sequence view, the site has gain of CDK1 and six other predicted losses
https://activedriverdb.org/sequence/show/NM_000551
<img width="498" alt="screen shot 2017-08-15 at 5 37 00 am" src="https://user-images.githubusercontent.com/19268349/29310500-e75b905a-817b-11e7-99bc-cc3dc19ef28d.png">

**Comment by krassowski** [comment]
I can confirm. The network predictions are correct, there is an issue with the tooltip showing "loss" instead of "gain". I will investigate it further.

**Comment by krassowski** [comment]
My last commit fixed this issue; I reopened as I though it did not work but I just needed to reload cache of my browser.

**Comment by reimand0** [comment]
thanks!
