### ISSUE TITLE
page title

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#135]
this is what chrome displays on the tab currently:

![screen shot 2017-08-21 at 9 44 58 pm](https://user-images.githubusercontent.com/19268349/29545051-0b78f976-86ba-11e7-8591-845a7c3739e9.png)

we should call the tab "ActiveDriver - front page" instead. Also a tiny logo would be nice there

**Comment by krassowski** [comment]
Done.
