### ISSUE TITLE
"Search" button into main top menu?

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#137]
Hey - is it worth adding a link Search to the main menu on the front page as well as the following pages? I think it is not easy to find the detailed search page, and the currently first link Download is not very frequently used by most users I guess.

**Comment by krassowski** [comment]
I think that Kim also raised this issue in e-mails (proposing adding "Mutations" and "Proteins" links to the top menu).

What about adding "Mutations" and "Proteins" which would lead to advanced mutation search and advanced protein search and collapsing "Download" and "Contact us" into a "More" dropdown button?

**Comment by krassowski** [comment]
In 629bc900e313c377e479ec54be7c830c4ab3b99d I added an ability to nest menu entries.

Please see the current layout, experimentally changed on [activedriverdb.org](https://activedriverdb.org).
It has following entries:

> Tutorial | Search ↓ | Publications | More ↓ | Login/My datasets

where "Search" contains: "Mutations" and "Proteins", while "More" has "API" and "Contact Us".


PS. Another idea would be to have it like this:

> Tutorial | Publications | Advanced ↓ | Contact Us | Login/My datasets

and "Advanced" would encompass: "Mutations", "Proteins" and "API"

**Comment by reimand0** [comment]
This looks more compact indeed. Some small changes perhaps:

"download & API" can be one menu item and one page, these fit well together.
"contact us" should be visible at all times, let's lift it out of the
dropdown.

**Comment by krassowski** [comment]
After lifting "Contact us" and moving "API" to "More" (so it is together with "Download", though not merged into a single entry yet) the menu does not fit in well on some of the tablet-sized screens:

![screenshot from 2017-09-27 16-15-10](https://user-images.githubusercontent.com/5832902/30924781-e737a9c8-a396-11e7-89db-ef4b8f9194e2.png)

**Comment by reimand0** [comment]
ok, nice catch. we can replace "contact us " with "contact". "More" is also
quite ambiguous, maybe use "Get"? would that sound better?

**Comment by krassowski** [comment]
I replaced "contact us" with "contact". As we decided to use "More" to link to a new page ("Acknowledgements") I will close it for now.

Please reopen or add a comment if any other menu changes are required.

PS. You can edit the menu when logged in using [this page](https://activedriverdb.org/list_menus/).
