### ISSUE TITLE
add message to empty networks

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#138]
We should add a message to empty experimental networks where no interactions are present (PIK3CA). One reviewer pointed this out.

**Comment by krassowski** [comment]
Done. The message shows up for both:
- proteins where there are no interactions at all (example: [PIK3CA](https://activedriverdb.org/network/show/NM_006218)) and,
- for such cases when we have some interactions but the active filters exclude all of them (e.g. [methylation in BRCA1](https://activedriverdb.org/network/show/NM_007294?filters=Site.type:in:methylation)).

**Comment by krassowski** [comment]
This concern was earlier addressed in 70fd39e35a38ff6a0adffe4bda63a2cea9bcd665 too.

**Comment by krassowski** [comment]
I improved the message to address empty the predicted networks too: https://activedriverdb.org/network/predicted/NM_007294?filters=Mutation.mc3_cancer_code:in:GBM
