### ISSUE TITLE
sort uploaded mutations

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#139]
We should be able to sort mutations in the table of uploaded mutations. I think the best default view would be by gene/isoform/protein_position so that adjacent mutations would show up close to one another.

**Comment by krassowski** [comment]
I made tables with uploaded mutations sortable.

The default action is **not** to sort as for bigger datasets and slower machines it could render the page unresponsive for some time; instead a button for sorting with the proposed criteria is exposed to the user:

![screenshot from 2017-11-22 23-08-27](https://user-images.githubusercontent.com/5832902/33154741-1bc7541c-cfda-11e7-88f4-b9ef7e048970.png)

As an alternative, we could perform the multi-sort server-side, during the search itself, possibly using heap sort so the whole procedure should be quite effective; the only drawback is that it will add some additional complexity to the code. Even if we perform the first (default) sort on the server-side, the "sort" button will be useful to allow user to revert to default order.

Here is how it look now:

![ezgif-5-ca2adcc453](https://user-images.githubusercontent.com/5832902/33154939-a2447a6e-cfdb-11e7-98ed-36dd86605ec2.gif)


Please let me know what do you think and if any improvements are needed.

**Comment by krassowski** [comment]
Closing for now, please feel free to reopen if any improvement is needed.
