### ISSUE TITLE
ClinVar disease annotations in Beta

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#141]
Looks like disease names of variants are missing in the beta version while all is in order in the stable release. Should be Disease Annotations: (ClinVar) HEMOGLOBIN LAS PALMAS, HEMOGLOBIN COLIMA

https://beta.activedriverdb.org/mutation/show/NM_000518/50/C
https://www.activedriverdb.org/mutation/show/NM_000518/50/C

Also there's something wrong here: 
Type: MutableSet({'phosphorylation'})

**Comment by krassowski** [comment]
Fixed; I must have accidentally dropped "disease" table, but this highlighted another issue.

Both problems are fixed now.

**Comment by krassowski** [comment]
There was also a problem with loading sequence view for proteins which had too much of filters (e.g. lots of disease names, as in HBB). This was fixed in acd34751f9fbb271108b15d6f1273d9fcfefcb27 and 55e1932a43a874a6d02060d426ea516de836a08c.
