### ISSUE TITLE
PTM sites to merge

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#2]
in the protein view, we should merge PTM flanking regions of individual PTM sites. 

For example:

site1 at S13 
site2 at S15

region1 is 13-7 until 13+7
region2 is 15-7 until 15+7
region_merged is 13-7 until 15+7

**Comment by krassowski** [comment]
what about flanking regions of different types of PTM sites? Currently those overlap (some appear on top of others) and this is not fully representative when all sites are shown. Maybe we can separate them, having four (or three, two or one if filters are applied) thinner tracks, one under another so full information is always shown?

**Comment by reimand0** [comment]
i think we can close this now. additional enhancements would perhaps make this more complex.
