### ISSUE TITLE
search form

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#22]
In the current version, we have two tab for searching. Instead let's have one page with two fields - a. smaller one-line field for gene/protein (grayed out value "TP53 or NM_000546")
b. larger multi-line field for mutations (grayed out value to include a few DNA and protein level mutations). 

there should be a button or link to "run example" that the user can run.

**Comment by reimand0** [comment]
Also, let's put a search form on every page. So in protein view, we can search for another protein without needing to go back to home page

**Comment by krassowski** [comment]
Is this issue still relevant?
