### ISSUE TITLE
tutorial to update input data for database

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#27]
we need a tutorial to update the database with new information or sites. This should be part of developer documentation, perhaps the github wiki.

**Comment by krassowski** [comment]
It's being developed here: [Wiki: How to add new datasets?](https://github.com/reimandlab/Visualisation-Framework-for-Genome-Mutations/wiki/How-to-add-new-datasets%3F) but still, there are some things to be done.

**Comment by krassowski** [comment]
I think that [the tutorial](https://github.com/reimandlab/ActiveDriverDB/wiki/How-to-add-new-datasets) it is mostly complete. Is there anything else I should add before closing this issue?

**Comment by krassowski** [comment]
Closing for now, please feel free to reopen if any improvement is needed.
