### ISSUE TITLE
Mutations counts in statistics does not sum up to total mutations count

### ISSUE THREAD

**Issue by krassowski** [reimandlab/ActiveDriverDB#46]
Current statistics indicate there might be some bug in counting or import script:
All: 2559719
ClinVar: 181457
TCGA: 478498
ESP 6500: 1319413
1K Genomes: 1071901

2559719 != 181457 + 478498 + 1319413 + 1071901

**Comment by krassowski** [comment]
After last update, the correct number of TCGA mutations is: 468115. Still does not resolves the issue.

**Comment by reimand0** [comment]
So half a million of extra mutations. There are many repeated mutations, especially between ESP and G1K . Are you counting unique mutations or repeated ones as well?

**Comment by krassowski** [comment]
All mutations on the left side are unique. I added script counting mutations which occur more than once, and it gives: 478779. To reproduce, use python script:
```python
from app import app
from statistics import stats
print(stats.from_many_sources())
```

So on the right side we have: `181457 + 468115 + 1319413 + 1071901 - 478779 = 2562107`
And comparing with the overall count: `2562107 - 2559719 = 2388`

It looks better but it indicates that still there are some duplicates or imperfections in scripts present.

**Comment by reimand0** [comment]
Maybe this small number corresponds to unannotated ClinVar mutations?

**Comment by krassowski** [comment]
After removal of  unannotated ClinVar mutations it's: `461384 - 459516 = 1868`. It might be an artefact of some wrongly removed mutations during some migrations in early versions of database. I will keep an eye on that and perform a complete database reload (from scratch) later on.

**Comment by reimand0** [comment]
let's revisit this after a database reload

**Comment by krassowski** [comment]
I finally found what was causing the issue. The overall mutation count was correct but the counts from specific sources (like ClinVar and 1KGenomes, but not from TCGA) contained some duplicates (for a less than 0.2% of records). For example greping our VCF-like file with `grep clinvar_muts_annotated.txt -e rs137852371` yields two results:

```
X	154194939	154194939	C	A	exonic	F8	.	nonsynonymous SNV	F8:NM_000132:exon8:c.G1033T:p.V345L	.	.	.	X	154194939	rs137852371	C	A,G	.	.	RS=137852371;RSPOS=154194939;RV;dbSNPBuildID=133;SSR=0;SAO=1;VP=0x050060000a05000002110100;GENEINFO=F8:2157;WGT=1;VC=SNV;PM;NSM;REF;ASP;LSD;OM;CLNALLE=1;CLNHGVS=NC_000023.10:g.154194939C>A;CLNSRC=OMIM_Allelic_Variant;CLNORIGIN=1;CLNSRCID=300841.0059;CLNSIG=5;CLNDSDB=MedGen:OMIM:OMIM:ORPHA:SNOMED_CT;CLNDSDBID=C0019069:134500:306700:98878:28293008;CLNDBN=Hereditary_factor_VIII_deficiency_disease;CLNREVSTAT=no_criteria;CLNACC=RCV000010855.5
X	154194939	154194939	C	G	exonic	F8	.	nonsynonymous SNV	F8:NM_000132:exon8:c.G1033C:p.V345L	.	.	.	X	154194939	rs137852371	C	A,G	.	.	RS=137852371;RSPOS=154194939;RV;dbSNPBuildID=133;SSR=0;SAO=1;VP=0x050060000a05000002110100;GENEINFO=F8:2157;WGT=1;VC=SNV;PM;NSM;REF;ASP;LSD;OM;CLNALLE=1;CLNHGVS=NC_000023.10:g.154194939C>A;CLNSRC=OMIM_Allelic_Variant;CLNORIGIN=1;CLNSRCID=300841.0059;CLNSIG=5;CLNDSDB=MedGen:OMIM:OMIM:ORPHA:SNOMED_CT;CLNDSDBID=C0019069:134500:306700:98878:28293008;CLNDBN=Hereditary_factor_VIII_deficiency_disease;CLNREVSTAT=no_criteria;CLNACC=RCV000010855.5
```
which are identical. For ClinVar alone there were 913 such duplicates in our database. Additionally there are 165 records which refer to the same mutation but differ by dbSNP id.

All such cases add up to missing 1580 mutations in the overall mutations count (that's different from the difference reported earlier as we obviously had a lot of changes in the database and there was a typo in function using inclusion-exclusion principle which was used to summarize mutations counts across multiple datasets - fixed in one of the commits above).

I already committed some changes which prevent such problems in the future and make the mutation counting more reliable. Those are not deployed to the server yet (I need to modify the scripts to show data from multiple dbSNP entries first).

Also mutations table in manuscript will need to be updated. (If I remember correctly only five fields will be affected, as all the other were calculated with the more reliable counting method).

**Comment by krassowski** [comment]
I dealt with the duplicated data and multiple rows for a single mutation for ClinVar (duplicates are now excluded on import, multiple dbsnp_id merged, PubMed presence and validation boolean values are set to true if these are set to true for any of dbsnp_ids).

The 1000 Genomes is a bigger problem as I cannot figure out how to merge such rows that map to a single mutation but have different MAF values. There are 243 such cases (0,023% of 1K Genomes mutations). @reimand0 could you have a look at this?

One example is SPN F330L mutation. There are two corresponding rows in our data files, one is TTC>CTC, the other one is TTC>TTG
```
zgrep G1000/G1000_chr16.hg19_multianno_nsSNV.txt.gz -e "F330L" | grep "SPN" | cut -f 1-22
```
Both have the same overall allele frequency (0.000199681) but differ with populations allele frequencies. (TTC>CTC has `SAS_AF=0.001`, and zeros elsewhere, TTC>TTG has `AFR_AF=0.0008` and zeros elsewhere):

```
16	29676037	29676037	T	C	exonic	SPN	.	nonsynonymous SNV	SPN:NM_001030288:exon2:c.T988C:p.F330L,SPN:NM_003123:exon2:c.T988C:p.F330L	0.0001997	100	15820	16	29676037	rs566277506	T	C	100	PASS	AC=1;AF=0.000199681;AN=5008;NS=2504;DP=15820;EAS_AF=0;AMR_AF=0;AFR_AF=0;EUR_AF=0;SAS_AF=0.001;AA=t|||;VT=SNP;EX_TARGET	GT
16	29676039	29676039	C	G	exonic	SPN	.	nonsynonymous SNV	SPN:NM_001030288:exon2:c.C990G:p.F330L,SPN:NM_003123:exon2:c.C990G:p.F330L	0.0001997	100	15808	16	29676039	rs539616054	C	G	100	PASS	AC=1;AF=0.000199681;AN=5008;NS=2504;DP=15808;EAS_AF=0;AMR_AF=0;AFR_AF=0.0008;EUR_AF=0;SAS_AF=0;AA=c|||;VT=SNP;EX_TARGET	GT
```

As for now only one of the rows is used. Should we show both values (altogether with the undermining DNA mutations) in sequence view?

**Comment by krassowski** [comment]
I fixed this, so now all frequencies will be shown, and the height of a needle for a specific mutation will be derived from sum of the frequencies. Also no exact duplicates will be imported in the first place. This seems that the issue is dealt with completely by now.

I will deploy the changes, run some tests, post a test case for future here and close the issue if everything goes well.

**Comment by krassowski** [comment]
The changes has been deployed and the mutations count are now all equal. I added the integrity test to documentation [server-side debugging documentation](https://github.com/reimandlab/ActiveDriverDB/wiki/Server-side:-Making-queries-and-debugging#are-mutation-counts-equal).

**Comment by reimand0** [comment]
Hey Michal - thanks, great job on fixing this. Such rare and complex
variant are unlikely to influence a lot of descisions, but summing up the
frequencies is probably the best choice now.
