### ISSUE TITLE
network visualisation - separate activated sub-network connected to site

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#69]
The spaced out network looks great, we should add this as default. 

We discussed an enhancement of this approach on the whiteboard. When user clicks on SiteX, site X will move to the right area of the canvas and take its binding kinases with it. This makes it easier to understand a specific site. 

Clicking on SiteX will release the network so it will move back to its original spot. Also clicking on SiteY will release SiteX. SiteY will move to right instead and SiteX will move back to original location. 

Adding picture below:

![img_1372](https://cloud.githubusercontent.com/assets/19268349/18794590/2ef125ae-818e-11e6-84bf-5e9abc4c23ce.JPG)

**Comment by krassowski** [comment]
I improved sub-network mechanism. Kinases in subnetworks are never overlapping now, the transition to subnetwork is smooth and peaceful; edge connecting subnetwork to the main network is visually singled out (grayed out and scaled up), jittering of tooltips which was happening during transition between main network and subnetworks is is dealt with. Activating second subnetwork (clicking on other kinase) makes the previous subnetwork hide.

Moreover sites in the main network are not overlapping now (collision detection is active always for sites rectangles; for kinases only when those are in active sub-network - if kinases where not to overlap all the time, it would be much less readable as those would need way much more space;  to keep kinases a little scattered a repulsive force is calculated between kinases in main network).

Please provide a feedback if any change is needed.

In my opinion one improvement could be to create a HUD-like interface. It would be displayed when sub-network is activated and show the same (or more) data as site tooltip; this could be just a text in corner of the canvas.

**Comment by krassowski** [comment]
Also I could add some quick positing filtering box. Right now its difficult to find a site of interest in busy networks (one can filter by type obviously but this might be not enough). Typing into filtering box would gray out sites that do not match given string (e.g. we can match by position but also by aminoacid or even by surrounding sequence). In simpler variant it could be a slider restricting positions from which sites are visible. Is it worth implementing any of those ideas?

**Comment by reimand0** [comment]
network view seems to be much faster and cleaner now, thanks!
