### ISSUE TITLE
example queries

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#76]
TP53 mutations in cancer (TCGA; protein, network view)
Noonan syndrome mutations in PTPN11 (ClinVar; protein, network view)

**Comment by krassowski** [comment]
I implemented required disease filter for ClinVar and created links on front page (https://activedriverdb.org/, example queries). I have chosen to include both "Noonan syndrome" and "Noonan syndrome 1" for the second set.
