### ISSUE TITLE
user-provided mutations from VCF stored in DB with session ID

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#83]
I would like to ask your opinion on implementing a way to upload user's mutation dataset into the database such that it becomes temporarily usable similarly to other mutation datasets (such as TCGA; the new dataset does not need to have subsets like TCGA-GBM though). This is necessary to open the capacity of our database in tables and visualisations to powerusers. 

One way to implement this involves a session ID that is given to the user. The dataset is stored with that session ID and the user can access it again when s/he comes back with the same user ID in the URL. I think MIMP software has something like this implemented - http://mimp.baderlab.org/

**Comment by krassowski** [comment]
Storing of user uploaded mutations (and their visualisation) is implemented for some time now. It may be further improved (as always), but we have all what was proposed herein. Shall we close this issue now?

**Comment by reimand0** [comment]
Let's close for now. I would expect new improvements as people start to use
this feature.
