### ISSUE TITLE
browsing genes by lists

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#88]
Lists of interesting use cases is one of the features we should have for novice and advanced users. 

ranked lists -
A. genes ranked* by number of PTM mutations in cancer
B. genes ranked* by number of PTM mutations in clinVar
* - we should rank by average number of mutations per amino acid, to avoid some extra long genes like TTN showing up in the list.

pathway lists - 
http://biit.cs.ut.ee/gprofiler/gmt/gprofiler_hsapiens.NAME.gmt.zip, in it the file hsapiens.pathways.NAME.gmt. This has quite a lot of gene lists associated to various biological processes and pathways. One line is one gene list (PW_ID TAB PW_name TAB gene1 TAB gene2 ..)
A. We can hand-pick some gene lists for user browsing. 
B. We should design an "advanced search" page or popup or tab where the user can search a particular pathway and a ranked list of genes would come out. 
* The genes in it should be also ranked as above. 

The advanced tab could also have search functions like according to disease (clinvar) or cancer type. The result would be a ranked list of genes with links to sequence and network view.

**Comment by krassowski** [comment]
I've created a prototype of pathways view: https://rl-db.oicr.on.ca/pathway/table/ (mostly ee67e25eb3f9216177a62caa351143d123d6734b)
It has server-side search & pagination and allows sorting by name/id. When clicking on a row it shows more information about genes involved in a particular pathway. I keep in mind implementing filters allowing to display only pathways with at least X and less than Y genes. I'll welcome any comments.

**Comment by krassowski** [comment]
So we have early versions of:
- Pathways list: https://rl-db.oicr.on.ca/pathway/table/
- Proteins list: https://rl-db.oicr.on.ca/protein/browse/

The problem right now is sorting. It takes some time: about 5-15 seconds to get results when sorting by relationship dependent counts (like by # mutations, # PTM sites, # genes). It depends on a simple SQL query and I am not sure if it can be improved (the query itself). I will play around with mysql configuration (tmp_table_size, max_heap_table_size), tables definitions, database-side functions, indices and so on to speed this up. I will add spinner to show user that fetching of data is ongoing and create filters we discussed.

Also when using descending sort on # genes in pathways' list the page size inflates quickly (the number of genes in the most occupied pathway makes the rendering of page very slow).

I am planning to implement the genes ranking described in this issue by:
- adding a column with "ranking value" to proteins table and making it the default to be used for sorting
- doing the same with a table shown in details of a pathways row (the subtable displayed after clicking on a row in pathways table)

The hardest thing seems to be to separate the proteins lists by mutations type (mutations in cancer, mutations in clinvar) and make a query which will determine quickly which mutations are affecting PTM sites. It might require some database schema changes to make it fast enough to provide seamless user experience.

**Comment by krassowski** [comment]
> The hardest thing seems to be to separate the proteins lists by mutations type (mutations in cancer, mutations in clinvar) and make a query which will determine quickly which mutations are affecting PTM sites. It might require some database schema changes to make it fast enough to provide seamless user experience.

just to explain why it might be difficult to do so quickly: we do this already for single proteins (in a reasonable time), but now we want to do this for all proteins in the database in order to sort them later. One option would be to precompute some things (this will break normalization of the database further, but I understand it's not a big issue since it's a static* database).

*by static I mean not supposed to be edited by anyone but a person running import scripts.

**Comment by reimand0** [comment]
fewer clicks is better. let's add two links to main page:

top genes with PTM mutations in cancer
top genes with PTM mutations in inherited disease

**Comment by reimand0** [comment]
going to list to protein. can you go back from the protein view to the list view?

**Comment by krassowski** [comment]
the links are done

**Comment by reimand0** [comment]
- filter pathways by FDR<0.05
- filter pathways so that only pathways with at least 5 genes are kept in the list
- sort by p-value
- if these are cancer pathways from TCGA data, then this should be said in the title

**Comment by reimand0** [comment]
alternative solution:
 - take Reactome pathways
 - only those that have >10 and <500 genes
 - and only those where at least 5 genes are in the significant gene list
 - one set of pathways for TCGA, another for ClinVar

**Comment by krassowski** [comment]
This is done, using the "alternative solution": https://activedriverdb.org/pathways/

**Comment by reimand0** [comment]
Thanks, looks good. When clicking on a gene link we should get directly to
the sequence view, not through isoform mapping.
