### ISSUE TITLE
download page

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#95]
we should have a couple of simple datasets on the download page:

1. all cancer mutations affecting PTM sites
2. all disease mutations affecting PTM sites
3. all population variants affecting PTM sites
4. site-specific network of kinases and targets

**Comment by reimand0** [comment]
about point 4:

column1 - kinase symbol
column2 - target symbol
column3 - kinase refseq
column4 - target refseq
column5 - target sequence position
column6 - target amino acid

**Comment by krassowski** [comment]
ad. column3: kinase refseq - sometimes kinases do not have proteins associated with them - should such kinases be included with empty column2 ? What about kinase groups - should those be included as well?

**Comment by krassowski** [comment]
The requested datasets are available to download on activedriver.org: [https://activedriverdb.org/download/](https://activedriverdb.org/download/).

**Comment by krassowski** [comment]
Closing for now, please feel free to reopen if any improvement is needed.
