### ISSUE TITLE
front page edits

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#96]
Let's make the front page more user friendly and focused. 

1. let's move a large and attractive but simple SEARCH BAR in the middle of the page. perhaps surround it with a box of pastel color to better stand out. Ideally the same box would search for gene name and mutation, but if not, then let's add two boxes. Both should have grayed out example text that could be queried. An additional link "Advanced search" will point to the page "Search for a protein or set of mutations". 

2. under search bar we should have example queries, like TP53 and PTPN11. large font links point to sequence view.
<large font>TP53</large font>
<small font>sequence | network</small font>

3. under that, we could have four smaller pastel color boxes, perhaps with different tones: 
- top genes in cancer, 
- top genes in inherited disease,
- top pathways in cancer,
- top pathways in inherited disease (do we have that data?)

4. under that, we should have a box with the welcome text. I will start writing this tomorrow but for now we have the previous text ready (about the data).

5. Under that, we could have Summary of Database and the table with all the numbers. Perhaps a one-column table will look simpler. Let's review the various names in the table later.

**Comment by krassowski** [comment]
Shall we close this issue as the new design is in?

**Comment by reimand0** [comment]
yes!
