### ISSUE TITLE
looking up amino acids in sequence view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActiveDriverDB#99]
![screen shot 2017-06-30 at 10 04 58 am](https://user-images.githubusercontent.com/19268349/27739166-a9497d3c-5d7b-11e7-8d87-0d16a860bba7.png)

how does this work? I tried to insert single numbers and ranges and it did not work for me

**Comment by reimand0** [comment]
gene is brca1

**Comment by krassowski** [comment]
Currently single numbers only. As this does not change zoom, you will not see it traveling to requested position until it was zoomed-in first. But I got it, it's not intuitive right now. Will add zoom and ranges.

**Comment by reimand0** [comment]
Thanks! in any case, an example value would be useful to have (perhaps as
greyed out in the form).

**Comment by krassowski** [comment]
I implemented the range queries and zooming. Does it work for you?
